//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admini
    {
        public int Aid { get; set; }
        public string Aadi { get; set; }
        public string Asoyadi { get; set; }
        public string Amaili { get; set; }
        public string Asifre { get; set; }
        public Nullable<bool> Aonay { get; set; }
        public Nullable<int> Kid { get; set; }
        public Nullable<int> Eid { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
