//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirimler
    {
        public int Bid { get; set; }
        public string Badi { get; set; }
        public string Bicerik { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<int> Kid { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
