//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevap
    {
        public int Cevapid { get; set; }
        public Nullable<System.DateTime> Cevaptrh { get; set; }
        public string Cevapdetay { get; set; }
        public Nullable<int> Soruid { get; set; }
        public Nullable<int> Kid { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Soru Soru { get; set; }
    }
}
