//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int Did { get; set; }
        public string Dbaslik { get; set; }
        public string Dicerik { get; set; }
        public Nullable<System.DateTime> Dtrh { get; set; }
        public Nullable<int> Eid { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
    }
}
