//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int Ktgrid { get; set; }
        public string Ktgradi { get; set; }
        public Nullable<int> Krsid { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
