//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dersportalEntities : DbContext
    {
        public dersportalEntities()
            : base("name=dersportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admini> Admini { get; set; }
        public virtual DbSet<Bildirimler> Bildirimler { get; set; }
        public virtual DbSet<Cevap> Cevap { get; set; }
        public virtual DbSet<Duyurular> Duyurular { get; set; }
        public virtual DbSet<Egitmen> Egitmen { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<KursIstatistik> KursIstatistik { get; set; }
        public virtual DbSet<Materyaller> Materyaller { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<Sertifikalar> Sertifikalar { get; set; }
        public virtual DbSet<Sinavlar> Sinavlar { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trendler> Trendler { get; set; }
    }
}
