//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sertifikalar
    {
        public int Srtid { get; set; }
        public string Srtadi { get; set; }
        public string Srticerik { get; set; }
        public Nullable<int> Snvid { get; set; }
    
        public virtual Sinavlar Sinavlar { get; set; }
    }
}
