//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinavlar()
        {
            this.Sertifikalar = new HashSet<Sertifikalar>();
        }
    
        public int Snvid { get; set; }
        public string Snvadi { get; set; }
        public string Snvicerik { get; set; }
        public Nullable<bool> BasariliMi { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<int> Kid { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sertifikalar> Sertifikalar { get; set; }
    }
}
