//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trendler
    {
        public int Tid { get; set; }
        public Nullable<int> KIid { get; set; }
    
        public virtual KursIstatistik KursIstatistik { get; set; }
    }
}
